# Generated by Django 4.2.1 on 2023-09-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
